---
title: "Interspeech"
author: "Irene Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidybayes)
library(wesanderson)
library(adehabitatHR)
```

```{r}
bhatt <- function (F1, F2, vowel) 
{
  vowel_data <- droplevels(data.frame(vowel))
  
  sp_df <- tryCatch(
    expr=SpatialPointsDataFrame(na.omit(cbind(F1, F2)), vowel_data), 
    error=function(e){NA})
  tryCatch(
    expr = {kerneloverlap(sp_df, method='BA')[1,2]}, 
    error = function(e){NA})
}
```


## Data processing

read in raw data
```{r}
NorthTown_raw <- readRDS("../data/eval_2_revisions/SLAAP-NorthTown_US_South_data.rds")
Sunset_raw <- readRDS("../data/eval_2_revisions/Sunset_US_West_data.rds")
Hastings_raw <- readRDS("../data/eval_2_revisions/Hastings_England_East_data.rds")
SOTC_raw <- readRDS("../data/eval_2_revisions/SOTC_Scotland_West_data.rds")

data_raw <- bind_rows(`SLAAP-NorthTown` = NorthTown_raw,
                      `Sunset` = Sunset_raw,
                      `Hastings` = Hastings_raw,
                      `SOTC` = SOTC_raw,
                      .id = "corpus") %>%
  dplyr::select(speaker, word, context, stressed_vowel, zF1, zF2, corpus) %>%
  mutate(model_type="empirical", 
         model_structure="raw")

data_ave <- data_raw %>%
  group_by(corpus, speaker, word) %>%
  summarise(zF1=mean(zF1),
            zF2=mean(zF2),
            context=first(context),
            stressed_vowel=first(stressed_vowel)) %>%
  ungroup() %>%
  mutate(model_type="empirical",
         model_structure="averaged")
```
Read in modeled data
```{r}
sp_predicted <- readRDS("../data/predicted_dataframes/Interspeech/predicted_sp.rds")
av_predicted <- readRDS("../data/predicted_dataframes/Interspeech/predicted_av.rds") 

sp_fitted <- readRDS("../data/predicted_dataframes/Interspeech/fitted_sp.rds")
av_fitted <- readRDS("../data/predicted_dataframes/Interspeech/fitted_av.rds")
```

factor levels
```{r}
vowel_levels=c("i", "e")
vowel_labels=c("/ɪ/", "/ɛ/") # sprintf('/\u026A/')
model_structure_levels=c("raw", "averaged", "m1", "m2")
model_structure_labels=c("raw", "averaged", "minimal", "expanded")
model_type_levels=c("empirical", "m", "u")
model_type_labels=c("empirical", "multivariate", "univariate")
corpus_levels=c("SLAAP-NorthTown", "Sunset", "Hastings", "SOTC")
corpus_labels=c("US South", "North Am.", "Eng. South", "Scotland")
model_levels=levels=c("empirical\nraw", "empirical\naveraged", 
                      "univariate\nminimal", "multivariate\nminimal", 
                      "univariate\nexpanded", "multivariate\nexpanded")
colors <- wes_palette("Cavalcanti1", n=2)
```


combine empirical and modeled dataframes
```{r}
sp_data <- sp_predicted %>%
  bind_rows(dplyr::select(data_raw, -word)) %>%
  bind_rows(dplyr::select(data_ave, -word)) %>%
  mutate(stressed_vowel=factor(stressed_vowel, levels=vowel_levels, labels=vowel_labels),
         model_structure=factor(model_structure, levels=model_structure_levels, labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels, labels=model_levels))
  
av_data <- av_predicted %>%
  bind_rows(dplyr::select(data_raw, -word, -speaker)) %>%
  bind_rows(dplyr::select(data_ave, -word, -speaker)) %>%
  mutate(stressed_vowel=factor(stressed_vowel, levels=vowel_levels, labels=vowel_labels),
         model_structure=factor(model_structure, levels=model_structure_levels, labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels, labels=model_levels))
```

Empirical Bhattacharyya affinity calculations
```{r}
BA_raw_sp <- data_raw %>%
  group_by(corpus, speaker, context) %>%
  summarise(bhatt_aff = bhatt(zF1, zF2, stressed_vowel),
            model_type=first(model_type),
            model_structure=first(model_structure)) %>%
  ungroup()
BA_ave_sp <- data_ave %>%
  group_by(corpus, speaker, context) %>%
  summarise(bhatt_aff = bhatt(zF1, zF2, stressed_vowel),
            model_type=first(model_type),
            model_structure=first(model_structure)) %>%
  ungroup()
```
Combine BA for 
```{r}
# BA_sp <- readRDS("../data/BA_calcs/Interspeech/bhattacharyya_affs_sp.rds") %>%
#   mutate(model_type = str_split_fixed(corpus, "_", 3)[,2],
#          model_structure = str_split_fixed(corpus, "_", 3)[,3],
#          corpus = str_split_fixed(corpus, "_", 3)[,1]) %>%
#   bind_rows(BA_raw_sp, BA_ave_sp) %>%
#   mutate(model_structure=factor(model_structure, levels=c("raw", "word av.", "m1", "m2"), labels=c("raw", "word av.", "minimal", "controls")),
#          model_type=factor(model_type, levels=c("empirical", "m", "u"), labels=c("empirical", "multivariate", "univariate")),
#          corpus=factor(corpus, levels=c("SLAAP-NorthTown", "Sunset", "Hastings", "SOTC"), 
#                        labels=c("US South", "North Am.", "England South", "Scotland"))) %>%
#   mutate(model=paste(model_type, model_structure, sep="\n")) %>%
#   mutate(model=factor(model, levels=c("empirical\nraw", "empirical\nword av.", 
#                                       "univariate\nminimal", "multivariate\nminimal", 
#                                       "univariate\ncontrols", "multivariate\ncontrols")))

BA_sp <- readRDS("../data/BA_calcs/Interspeech/bhattacharyya_affs_sp.rds") %>%
  mutate(model_type = str_split_fixed(corpus, "_", 3)[,2],
         model_structure = str_split_fixed(corpus, "_", 3)[,3],
         corpus = str_split_fixed(corpus, "_", 3)[,1]) %>%
  bind_rows(BA_raw_sp, BA_ave_sp) %>%
  mutate(model_structure=factor(model_structure, levels=model_structure_levels,
                                labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, 
                           labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, 
                       labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels))

BA_av <- readRDS("../data/BA_calcs/Interspeech/bhattacharyya_affs_av.rds") %>%
  mutate(model_type = str_split_fixed(corpus, "_", 3)[,2],
         model_structure = str_split_fixed(corpus, "_", 3)[,3],
         corpus = str_split_fixed(corpus, "_", 3)[,1]) %>%
  bind_rows(dplyr::select(BA_raw_sp, -speaker), dplyr::select(BA_ave_sp, -speaker)) %>%
  mutate(model_structure=factor(model_structure, levels=model_structure_levels,
                                labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, 
                           labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, 
                       labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels))
```



```{r}
ED_raw_sp <- data_raw %>%
  group_by(corpus, speaker, context, stressed_vowel) %>%
  summarise(zF1=mean(zF1),
            zF2=mean(zF2),
            model_type=first(model_type),
            model_structure=first(model_structure)) %>%
  ungroup() %>%
  pivot_wider(names_from="stressed_vowel", values_from=c("zF1", "zF2")) %>%
  mutate(eucl_dist = sqrt((zF1_i - zF1_e)^2 + (zF2_i - zF2_e)^2))

ED_ave_sp <- data_ave %>%
  group_by(corpus, speaker, context, stressed_vowel) %>%
  summarise(zF1=mean(zF1),
            zF2=mean(zF2), 
            model_type=first(model_type),
            model_structure=first(model_structure)) %>%
  ungroup() %>%
  pivot_wider(names_from="stressed_vowel", values_from=c("zF1", "zF2")) %>%
  mutate(eucl_dist = sqrt((zF1_i - zF1_e)^2 + (zF2_i - zF2_e)^2))
  
```


```{r}
ED_sp <- sp_fitted %>%
  dplyr::select(-.row, -.chain, -.iteration) %>%
  pivot_wider(names_from="stressed_vowel", values_from=c("zF1", "zF2")) %>%
  mutate(eucl_dist = sqrt((zF1_i - zF1_e)^2 + (zF2_i - zF2_e)^2)) %>%
  bind_rows(ED_raw_sp, ED_ave_sp) %>%
  mutate(model_structure=factor(model_structure, levels=model_structure_levels, 
                                labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, 
                           labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, 
                       labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels))

ED_av <- av_fitted %>%
  dplyr::select(-.row, -.chain, -.iteration) %>%
  pivot_wider(names_from="stressed_vowel", values_from=c("zF1", "zF2")) %>%
  mutate(eucl_dist = sqrt((zF1_i - zF1_e)^2 + (zF2_i - zF2_e)^2)) %>%
  bind_rows(dplyr::select(ED_raw_sp, -speaker), dplyr::select(ED_ave_sp, -speaker)) %>%
  mutate(model_structure=factor(model_structure, levels=model_structure_levels, 
                                labels=model_structure_labels),
         model_type=factor(model_type, levels=model_type_levels, 
                           labels=model_type_labels),
         corpus=factor(corpus, levels=corpus_levels, 
                       labels=corpus_labels)) %>%
  mutate(model=paste(model_type, model_structure, sep="\n")) %>%
  mutate(model=factor(model, levels=model_levels))
  
# ED_av <- av_fitted %>%
#   dplyr::select(-.row, -.chain, -.iteration) %>%
#   pivot_wider(names_from="stressed_vowel", values_from=c("zF1", "zF2")) %>%
#   mutate(eucl_dist = sqrt((zF1_i - zF1_e)^2 + (zF2_i - zF2_e)^2)) %>%
#   mutate(model_structure=factor(model_structure, levels=c("m1", "m2"), labels=c("minimal", "controls")),
#          model_type=factor(model_type, levels=c("m", "u"), labels=c("multivariate", "univariate")),
#          corpus=factor(corpus, levels=c("SLAAP-NorthTown", "Sunset", "Hastings", "SOTC"), 
#                        labels=c("US South", "North Am.", "England South", "Scotland")))
```

```{r, fig.width=7, fig.height=7}
av_data %>%
  filter(model_structure!="averaged", model_type!="univariate") %>%
  ggplot(aes(x=zF2, y=zF1)) +
  # geom_point(alpha=0.001, aes(color=context)) +
  stat_ellipse(size=0.3, level=0.1, aes(color=context, lty=stressed_vowel)) +
  # geom_point(alpha=0.5, aes(color=context)) +
  facet_grid(model_structure~corpus) +
  scale_x_reverse() + scale_y_reverse() +
  scale_color_manual(values=colors) +
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=6),
        axis.text.y=element_text(size=6),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        legend.position="bottom", legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/distributions_Interspeech.pdf", 
       width=80, height=77, units = "mm", 
       device=cairo_pdf)
```

```{r, fig.width=15, fig.height=15}
data_raw %>%
  filter(corpus=="SLAAP-NorthTown") %>%
  ggplot(aes(x=zF2, y=zF1)) +
  scale_shape_manual(values = c(21, 22)) +
  # geom_point(alpha=0.25, size=0.5, pch=21, aes(shape=stressed_vowel)) +
  geom_point(alpha=0.25, size=0.5, stroke=0.05, aes(fill=context, shape=stressed_vowel)) +
  stat_ellipse(size=0.3, level=0.66, aes(color=context, lty=stressed_vowel)) +
  # geom_point(alpha=0.5, aes(color=context)) +
  facet_wrap(~speaker) +
  scale_x_reverse() + scale_y_reverse() +
  scale_color_manual(values=colors) +
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=6),
        axis.text.y=element_text(size=6),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        legend.position="top", legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
```

```{r}
p_step1 <- sp_data %>%
  filter(model_structure=="raw", speaker=="ntn111k") %>%
  mutate(stressed_vowel=factor(stressed_vowel, labels=c("V1", "V2"))) %>%
  ggplot(aes(x=zF2, y=zF1)) +
  geom_point(alpha=0.5, size=3, stroke=0.05, #size=1
             aes(fill=context, shape=stressed_vowel), show.legend=FALSE) +
  stat_ellipse(size=1, level=0.66, # size=0.3
               aes(color=context, lty=stressed_vowel), show.legend=FALSE) +
  scale_x_reverse() + scale_y_reverse() +
  scale_shape_manual(values = c(23, 22)) +
  scale_fill_manual(values=colors) +
  scale_color_manual(values=colors) +
  xlim(2, -2) + ylim(2, -2) +
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15, vjust=-1 # , 
                                  # margin=margin(t=0, r=0, b=0, l=0, unit="cm")
                                  ),
        axis.ticks=element_blank(),
        # plot.margin=margin(t=0, r=0, b=0, l=0),
        plot.title=element_text(size=20)) +
  ggtitle("1: Preprocessing")
p_step1
```

```{r}
p_step2 <- sp_fitted %>%
  filter(model_structure=="m2", model_type=="m", speaker=="ntn111k") %>%
  pivot_longer(cols=starts_with("z"), names_to="formant") %>%
  group_by(context, stressed_vowel, formant) %>%
  mean_qi(value) %>%
  ungroup() %>%
  mutate(stressed_vowel=factor(stressed_vowel, labels=c("V1", "V2")),
         context=factor(context, labels=c("cond. env.", "elsewhere"))) %>%
  ggplot(aes(x=stressed_vowel, y=value)) +
  geom_line(size=1, 
            aes(color=context, group=interaction(context, formant)), 
            show.legend=FALSE) +
  geom_errorbar(size=1, width=0.2,# size=0.3
                aes(ymin=.lower, ymax=.upper, color=context, 
                    group=interaction(context, formant)), 
                show.legend=FALSE) +
  geom_point(size=5, aes(color=context, shape=formant), show.legend=FALSE) +
  scale_color_manual(values=colors) +
  theme_bw() +
  theme(axis.text.x=element_text(size=15),
        axis.text.y=element_blank(), 
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.y=element_blank(),
        # plot.margin=margin(t=0, r=0, b=0, l=0, unit="cm"),
        plot.title=element_text(size=20)) +
  ggtitle("2: Modelling")
p_step2
```

```{r}
p_step3 <- sp_data %>%
  filter(model_structure=="expanded", model_type=="multivariate", speaker=="ntn111k") %>%
  mutate(stressed_vowel=factor(stressed_vowel, labels=c("V1", "V2"))) %>%
  ggplot(aes(x=zF2, y=zF1)) +
  stat_ellipse(size=1, level=0.66, aes(color=context, lty=stressed_vowel),
               show.legend=FALSE) +
  scale_x_reverse() + scale_y_reverse() +
  scale_shape_manual(values = c(23, 22)) +
  scale_color_manual(values=colors) +
  xlim(2, -2) + ylim(2, -2) +
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_text(size=15), # 6
        axis.title.y=element_text(size=15, vjust=-1 # , 
                                  # margin=margin(t=0, r=0.2, b=0, l=0, unit="cm")
                                  ),
        # plot.margin=margin(t=0, r=0.25, b=0, l=0, unit="cm"),
        plot.title=element_text(size=20)) + # 8
  ggtitle('3: Simulation')
p_step3
```
```{r}
p_step4 <- BA_sp %>%
  filter(model_structure=="expanded", model_type=="multivariate", speaker=="ntn111k") %>%
  group_by(context) %>%
  mean_qi(bhatt_aff) %>%
  ungroup() %>%
  mutate(context=factor(context, labels=c("cond.\nenv.", "else-\nwhere"))) %>%
  ggplot(aes(x=context, y=bhatt_aff)) +
  geom_point(size=5, aes(color=context), show.legend=FALSE) + # size=default
  geom_errorbar(size=1, width=0.2, # size=0.3
                aes(ymin=.lower, ymax=.upper, color=context), 
                show.legend=FALSE) +
  scale_colour_manual(values=colors) +
  ylim(0, 1) +
  theme_bw() +
  theme(axis.text.x=element_text(size=15),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.ticks.y=element_blank(),
        # plot.margin=margin(t=0, r=0, b=0, l=0, unit="cm"),
        plot.title=element_text(size=20)) +
  ggtitle("4: Overlap")
p_step4
```

```{r}
p_process <- p_step1 + p_step2 + p_step3 + p_step4 +
  plot_layout(widths=unit(c(21, 1, 21, 1), c('mm', 'null', 'mm', 'null')),
              heights=unit(c(20), c('mm')), 
              ncol=4) +
  plot_annotation(theme=theme(
    plot.margin=margin(t=0, r=0, b=0, l=0, unit="null"))) # & 
  # theme(legend.position='bottom', 
  #       legend.box.spacing=unit(0, 'pt'),
  #       legend.spacing.y=unit(0, 'null'),
  #       legend.margin=margin(t=0, r=0, b=0, l=0, unit='pt'),
  #       legend.box='horizontal',
  #       # legend.justification=c(0, 0)
  #       )

p_process
ggsave("../plots/process_Interspeech_South_v2.pdf", 
       width=82, height=34, units = "mm", 
       device=cairo_pdf)
```

```{r}
p_process <- p_step1 + p_step2 + p_step3 + p_step4 +
  plot_layout(widths=unit(c(9.5, 1, 9.5, 1), c('cm', 'null', 'cm', 'null')),
              heights=unit(c(9.5), c('cm')), 
              ncol=4) +
  plot_annotation(theme=theme(
    plot.margin=margin(t=0, r=0, b=0, l=0, unit="null"))) # & 
  # theme(legend.position='bottom', 
  #       legend.box.spacing=unit(0, 'pt'),
  #       legend.spacing.y=unit(0, 'null'),
  #       legend.margin=margin(t=0, r=0, b=0, l=0, unit='pt'),
  #       legend.box='horizontal',
  #       # legend.justification=c(0, 0)
  #       )

p_process
ggsave("../plots/asa_process.jpg", 
       width=38, height=16, units = "cm")
```


```{r}
ggsave("../plots/process_Interspeech_South.pdf", 
       width=80, height=80, units = "mm", 
       device=cairo_pdf)
```

```{r, fig.height=7, fig.width=7}
BA_sp %>%
  group_by(speaker, model, context, corpus) %>%
  summarise(bhatt_aff = mean(bhatt_aff)) %>%
  pivot_wider(names_from="context", values_from="bhatt_aff") %>%
  ggplot(aes(x=oral, y=nasal)) +
  geom_point(size=1, alpha=0.25) + 
  facet_grid(model~corpus) + 
  geom_abline(size=0.3, lty=3) +
  xlab("preoral Bhattacharyya affinity") +
  ylab("prenasal Bhattacharyya affinity") +
  xlim(0,1) + ylim(0,1) + 
  coord_fixed() +
  theme_bw(base_size=10) +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=6),
        axis.text.y=element_text(size=6),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        legend.position="top", legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/BA_Interspeech_triangle.pdf", 
       width=80, height=110, units = "mm", 
       device=cairo_pdf)
```

Distance version of BA (sqrt(1-BA))
```{r, fig.height=7, fig.width=7}
BA_sp %>%
  group_by(speaker, model, context, corpus) %>%
  summarise(bhatt_aff = sqrt(1-mean(bhatt_aff))) %>%
  pivot_wider(names_from="context", values_from="bhatt_aff") %>%
  ggplot(aes(x=oral, y=nasal)) +
  geom_point(size=1, alpha=0.25) + 
  facet_grid(model~corpus) + 
  geom_abline(size=0.3, lty=3) +
  xlab("oral Hellinger distance") +
  ylab("nasal Hellinger distance") +
  xlim(0,1) + ylim(0,1) + 
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=6),
        axis.text.y=element_text(size=6),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        legend.position="top", legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/HD_Interspeech_triangle.pdf", 
       width=80, height=110, units = "mm", 
       device=cairo_pdf)
```



```{r, fig.height=7, fig.width=7}
ED_sp %>%
  filter(model_type!="univariate") %>%
  group_by(speaker, model, context, corpus) %>%
  summarise(eucl_dist = mean(eucl_dist)) %>%
  pivot_wider(names_from="context", values_from="eucl_dist") %>%
  ggplot(aes(x=oral, y=nasal)) +
  geom_point(size=1, alpha=0.25) + 
  facet_grid(model~corpus) + 
  geom_abline(size=0.3, lty=3) +
  xlab("preoral Euclidean distance") +
  ylab("prenasal Euclidean distance") +
  # xlim(0,1) + ylim(0,1) + 
  coord_fixed() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=6),
        axis.text.y=element_text(size=6),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        legend.position="top", legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/ED_Interspeech_triangle.pdf", 
       width=80, height=80, units = "mm", 
       device=cairo_pdf)
# ggsave("../plots/ED_Interspeech_triangle.png")
```

```{r}
BA_av %>%
  # group_by(speaker, model_type, model_structure, context, corpus) %>%
  # summarise(bhatt_aff = mean(bhatt_aff)) %>%
  filter(model_type!="empirical") %>%
  pivot_wider(names_from="context", values_from="bhatt_aff") %>%
  ggplot(aes(x=oral, y=nasal)) +
  geom_point(alpha=0.25) + 
  facet_grid(model~corpus) + 
  geom_abline(lty=2) +
  xlim(0,1) + ylim(0,1) + 
  coord_fixed()
```

```{r}
ED_av %>%
  # group_by(speaker, model_type, model_structure, context, corpus) %>%
  # summarise(eucl_dist = mean(eucl_dist)) %>%
  dplyr::select(-zF1_i, -zF1_e, -zF2_i, -zF2_e) %>%
  pivot_wider(names_from="context", values_from="eucl_dist") %>%
  ggplot(aes(x=oral, y=nasal)) +
  geom_point(alpha=0.25) + 
  facet_grid(model_structure+model_type~corpus) + 
  geom_abline(lty=2) +
  # xlim(0,1) + ylim(0,1) + 
  coord_fixed()
```


Average BA by method
```{r, fig.width=8, fig.height=5}
BA_av %>%
  filter(model_type!="univariate") %>%
  group_by(model_type, model_structure, context, corpus) %>%
  # summarise(n=n()) %>%
  # ungroup()
  mean_qi(bhatt_aff, na.rm=TRUE) %>%
  mutate(.lower=case_when(model_type=="empirical" ~ NA,
                          TRUE~.lower),
         .upper=case_when(model_type=="empirical" ~ NA,
                          TRUE~.upper)) %>%
  ggplot(aes(x=corpus, y=bhatt_aff, color=context)) +
  # geom_pointrange(alpha=0.75, size=0.75, aes(ymax=.upper, ymin=.lower)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  facet_wrap(~model_structure) +
  ylab("Mean BA with 95% QIs") +
  scale_color_manual(values=colors) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/BA_Interspeech_av_model.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)
# ggsave("../plots/BA_Interspeech_av_model.png")
```

Average BA by dialect
```{r, fig.width=8, fig.height=5}
BA_av %>%
  filter(model_type!="univariate") %>%
  group_by(model_type, model_structure, context, corpus) %>%
  mean_qi(bhatt_aff, na.rm=TRUE) %>%
  mutate(.lower=case_when(model_type=="empirical" ~ NA,
                          TRUE~.lower),
         .upper=case_when(model_type=="empirical" ~ NA,
                          TRUE~.upper)) %>%
  ggplot(aes(x=model_structure, y=bhatt_aff, color=context)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  # geom_pointrange(alpha=0.75, size=0.08, aes(ymax=.upper, ymin=.lower)) +
  facet_wrap(~corpus) +
  ylab("Mean BA with 95% QIs") +
  theme_bw(base_size=10) +
  # theme(axis.text.x=element_text(size=8, angle=45, hjust=1, vjust=1),
  #       axis.title.x = element_blank(),
  #       legend.text=element_text(size=8),
  #       )
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/BA_Interspeech_av_dialect.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)
```


```{r, fig.width=8, fig.height=5}
BA_av %>%
  filter(model_type!="univariate") %>%
  mutate(hell_dist=sqrt(1-bhatt_aff)) %>%
  group_by(model_type, model_structure, context, corpus) %>%
  # summarise(n=n()) %>%
  # ungroup()
  mean_qi(hell_dist, na.rm=TRUE) %>%
  ggplot(aes(x=corpus, y=hell_dist, color=context)) +
  # geom_pointrange(alpha=0.75, size=0.75, aes(ymax=.upper, ymin=.lower)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  facet_wrap(~model_structure) +
  ylab("Mean HD with 95% QIs") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/HD_Interspeech_av_model.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)

# ggsave("../plots/BA_Interspeech_av_model.png")
```


```{r, fig.width=8, fig.height=5}
BA_av %>%
  filter(model_type!="univariate") %>%
  mutate(hell_dist=sqrt(1-bhatt_aff)) %>%
  group_by(model_type, model_structure, context, corpus) %>%
  mean_qi(hell_dist, na.rm=TRUE) %>%
  ggplot(aes(x=model_structure, y=hell_dist, color=context)) +
  # geom_pointrange(alpha=0.75, size=0.75, aes(ymax=.upper, ymin=.lower)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  facet_wrap(~corpus) +
  ylab("Mean HD with 95% QIs") +
  theme_bw(base_size=10) +
  # theme(axis.text.x=element_text(size=8, angle=45, hjust=1, vjust=1)) +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/HD_Interspeech_av_dialect.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)
# ggsave("../plots/BA_Interspeech_av_dialect.pdf", width=80, height=60, units = "mm")
```

Average ED by model
```{r, fig.width=8, fig.height=5}
ED_av %>%
  filter(model_type!="univariate") %>%
  group_by(model_type, model_structure, context, corpus) %>%
  # summarise(n=n()) %>%
  # ungroup()
  mean_qi(eucl_dist, na.rm=TRUE) %>%
  ggplot(aes(x=corpus, y=eucl_dist, color=context)) +
  # geom_pointrange(alpha=0.75, size=0.75, aes(ymax=.upper, ymin=.lower)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  facet_wrap(~model_structure) +
  ylab("Mean ED with 95% QIs") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/ED_Interspeech_av_model.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)
# ggsave("../plots/BA_Interspeech_av_model.png")
```
Average ED by dialect
```{r, fig.width=8, fig.height=5}
ED_av %>%
  filter(model_type!="univariate") %>%
  group_by(model_type, model_structure, context, corpus) %>%
  mean_qi(eucl_dist, na.rm=TRUE) %>%
  ggplot(aes(x=model_structure, y=eucl_dist, color=context)) +
  # geom_pointrange(alpha=0.75, size=0.75, aes(ymax=.upper, ymin=.lower)) +
  geom_errorbar(alpha=0.75, size=0.3, width=0.2, aes(ymax=.upper, ymin=.lower)) +
  geom_point(alpha=0.75, size=1) +
  facet_wrap(~corpus) +
  ylab("Mean ED with 95% QIs") +
  theme_bw(base_size=8) +
  # theme(axis.text.x=element_text(size=8, angle=45, hjust=1, vjust=1)) +
  theme(axis.text.x=element_text(angle=45, hjust=1, vjust=1, size=8),
        axis.text.y=element_text(size=6),
        axis.title.x = element_blank(),
        # axis.title.x=element_text(margin=margin(t=0, b=0)),
        # legend.position="top", 
        legend.title=element_blank(),
        legend.text=element_text(size=8),
        legend.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        legend.box.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        # strip.clip="off",
        plot.margin=margin(t=0, r=0, b=0, l=0, unit="pt"),
        panel.spacing=unit(0.75, "mm"),
        strip.text=element_text(size=8), axis.title=element_text(size=8))
ggsave("../plots/ED_Interspeech_av_dialect.pdf", 
       width=80, height=60, units = "mm", 
       device=cairo_pdf)
# ggsave("../plots/BA_Interspeech_av_dialect.pdf", width=80, height=60, units = "mm")
```
